spring:
  application:
    name: admin-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.r2dbc.ConnectionFactoryHealthContributorAutoConfiguration

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logbook: {}

logging:
    level:
      org.zalando.logbook: TRACE
      de.codecentric.boot.admin: WARN
      org.springframework.boot.actuate: WARN
      org.springframework.web: WARN