spring:
  application:
    name: admin-server

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

logbook: {}

logging:
    level:
      org.zalando.logbook: TRACE
      de.codecentric.boot.admin: WARN
      org.springframework.boot.actuate: WARN
      org.springframework.web: WARN