services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - cart-service
      - product-detail
    networks:
      - app-network
    environment:
      - JAVA_OPTS=-Xmx768m -Xms512m
    mem_limit: 1g
    mem_reservation: 512m

  admin-server:
    build:
      context: ./admin-server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - JAVA_OPTS=-Xmx768m -Xms512m
    mem_limit: 1g
    mem_reservation: 512m

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      db-migrations:
        condition: service_completed_successfully
    networks:
      - app-network
    environment:
      - JAVA_OPTS=-Xmx768m -Xms512m
    mem_limit: 1g
    mem_reservation: 512m

  product-catalog:
    build:
      context: ./product-catalog
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      db-migrations:
        condition: service_completed_successfully
    networks:
      - app-network
    environment:
      - JAVA_OPTS=-Xmx768m -Xms512m
    mem_limit: 1g
    mem_reservation: 512m

  product-detail:
    build:
      context: ./product-detail
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      db-migrations:
        condition: service_completed_successfully
    networks:
      - app-network
    environment:
      - JAVA_OPTS=-Xmx768m -Xms512m
    mem_limit: 1g
    mem_reservation: 512m

  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      db-migrations:
        condition: service_completed_successfully
    networks:
      - app-network
    environment:
      - JAVA_OPTS=-Xmx768m -Xms512m
    mem_limit: 1g
    mem_reservation: 512m

  orders-list:
    build:
      context: ./orders-list
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      db-migrations:
        condition: service_completed_successfully
    networks:
      - app-network
    environment:
      - JAVA_OPTS=-Xmx768m -Xms512m
    mem_limit: 1g
    mem_reservation: 512m

  order-detail:
    build:
      context: ./order-detail
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      db-migrations:
        condition: service_completed_successfully
    networks:
      - app-network
    environment:
      - JAVA_OPTS=-Xmx768m -Xms512m
    mem_limit: 1g
    mem_reservation: 512m

  purchase-service:
    build:
      context: ./purchase-service
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      db-migrations:
        condition: service_completed_successfully
    networks:
      - app-network
    environment:
      - JAVA_OPTS=-Xmx768m -Xms512m
    mem_limit: 1g
    mem_reservation: 512m

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 555666
      POSTGRES_MULTIPLE_DATABASES: userdb,productdb,cartdb,ordersdb,purchasedb
      POSTGRES_SHARED_BUFFERS: 512MB
      POSTGRES_WORK_MEM: 8MB
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    mem_limit: 2g
    mem_reservation: 1g

  db-migrations:
    build:
      context: ./db-migrations
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    mem_limit: 512m
    mem_reservation: 256m

networks:
  app-network: