spring:
  application:
    name: api-gateway
  server:
    port: 8080
  boot:
    admin:
      client:
        url: http://admin-server:8081

  cloud:
    gateway:
      routes:
        - id: product-detail
          uri: http://product-detail:8080
          predicates:
            - Path=/api/products/detail/**
          filters:
            - RewritePath=/api/products/detail/(?<segment>.*),/api/products/${segment}
        - id: product-catalog
          uri: http://product-catalog:8080
          predicates:
            - Path=/api/products/**
        - id: cart-service
          uri: http://cart-service:8080
          predicates:
            - Path=/api/cart/**
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/api/orders/**
        - id: purchase-service
          uri: http://purchase-service:8080
          predicates:
            - Path=/api/purchase/**
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/**
        - id: admin-server
          uri: http://admin-server:8081
          predicates:
            - Path=/admin/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,loggers
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    description: This is the ${spring.application.name} module.
    version: 1.0.0

logbook: {}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.zalando.logbook: TRACE
    org.zalando.logbook.netty: TRACE
    org.springframework.boot.actuate: WARN
    org.springframework.web: WARN
    io.opentelemetry: DEBUG