spring:
  application:
    name: wallet-service
  r2dbc:
    url: r2dbc:postgresql://db:5432/walletdb
    username: wallet_service_user
    password: wallet-service_password
    pool:
      max-size: 10
      min-idle: 5
      initial-size: 5
      max-idle-time: 30s
      max-create-connection-time: 30s
      max-life-time: 600s
      name: WalletServiceHikariPool
      validation-query: SELECT 1
      validation-query-timeout: 3s
  boot:
    admin:
      client:
        url: http://admin-server:8081
  cache:
    cache-names: wallets
    redis:
      time-to-live: PT5S
  data:
    redis:
      host: redis
      port: 6379
  security:
    oauth2:
      client:
        registration:
          wallet-service:
            client-id: wallet-service
            client-secret: Ree5ppd60XxCxKZKmVgF25NkYndfKEop
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/shop-realm/protocol/openid-connect/token
      resourceserver:
        jwt:
          jwk-set-uri: "http://keycloak:8080/realms/shop-realm/protocol/openid-connect/certs"

security-config:
  enabled: true
  permit-all-paths:
    - "/actuator/**"
  client-id: frontend-client
  jwk-set-uri: "http://keycloak:8080/realms/shop-realm/protocol/openid-connect/certs"
  allowed-roles:
    - "ROLE_USER"
    - "purchase-service"

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,loggers
  endpoint:
    health:
      show-details: always

health:
  wallet-service:
    table: wallets
    schema: public

info:
  app:
    name: ${spring.application.name}
    description: This is the ${spring.application.name} module.
    version: 1.0.0

logbook: {}

logging:
  level:
    org.zalando.logbook: TRACE
    org.zalando.logbook.netty: TRACE
    org.example: INFO
    org.example.util: INFO
    org.springframework.boot.actuate: WARN
    org.springframework.web: WARN
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.filter: WARN
    io.opentelemetry: DEBUG