spring:
  application:
    name: db-migrations

db:
  migrations:
    databases:
      orders:
        url: jdbc:postgresql://db:5432/ordersdb
        username: orders_service_user
        password: orders-service_password
        changelog: db/changelog/orders/changelog-orders.xml
      product:
        url: jdbc:postgresql://db:5432/productdb
        username: product_service_user
        password: product-service_password
        changelog: db/changelog/products/changelog-products.xml
      user:
        url: jdbc:postgresql://db:5432/userdb
        username: user_service_user
        password: user-service_password
        changelog: db/changelog/users/changelog-users.xml
      cart:
        url: jdbc:postgresql://db:5432/cartdb
        username: cart_service_user
        password: cart-service_password
        changelog: db/changelog/carts/changelog-cart.xml
      purchase:
        url: jdbc:postgresql://db:5432/purchasedb
        username: purchase_service_user
        password: purchase-service_password
        changelog: db/changelog/purchase/changelog-purchase.xml
      wallet:
        url: jdbc:postgresql://db:5432/walletdb
        username: wallet_service_user
        password: wallet-service_password
        changelog: db/changelog/wallets/changelog-wallets.xml

info:
  app:
    name: ${spring.application.name}
    description: This is the ${spring.application.name} module.
    version: 1.0.0